### PR TITLE
Allow to perform extra operations on template

### PR DESCRIPTION
**Pull request by wtrocki**
I was playing with the library and it seems pretty small and very limiting at the moment.
The main problem I found is that creato is killing the process and promise is never satisfied with prevents users from asking additional questions. This simple fix should allow us to hook up extra elements into the flow however it will be nicer if library will be made modular - so `loadTemplate` and `askForTemplateOptions` methods will be available for developers who need to perform much more than just ask simple question

### CODE REVIEW

**Comment by wtrocki** [comment]
ping @maticzav

**Comment by wtrocki** [comment]
Additionally I think that we should be passing picked template in Promise. WDYT?

**Comment by maticzav** [comment]
@wtrocki I think this is a great addition, thank you! Merging in a second 🙌

**Pull request merged**
